// Generated by CoffeeScript 1.12.7
(function() {
    $(document).ready(function() {
        $("#onoffswitch").on('click', function(){
            clickSwitch()
        });

        var clickSwitch = function() {
            if ($("#onoffswitch").is(':checked')) {
                localStorage.setItem('status', 1)
                // chrome.management.setEnabled('dcdjnbgafinaklkiiejdlakcklpfcngd', true, function a(){})
                console.log("在ON的状态下");
            } else {
                // chrome.management.setEnabled('dcdjnbgafinaklkiiejdlakcklpfcngd', false, function a(){})
                localStorage.setItem('status', 0)
                console.log("在OFF的状态下");
            }
        };
        if (localStorage.getItem('status') == '0'){
            $("#onoffswitch").prop("checked", false)
        }else
        {
            $("#onoffswitch").prop("checked", true)
        }

        chrome.extension.onMessage.addListener(
            function(request, sender, sendResponse) {
                sendResponse(localStorage.getItem('status'));
            }
        );
    });
}).call(this);
