// Generated by CoffeeScript 1.12.7
(function() {
  // 内网环境地址
  var URL = 'http://in.rccchina.com'
  // 客服/销售 制作划词快速搜索 http://in4.rccchina.com/fg/tasks/30935 by blank.nie
  RCC_REACH.search_text_by_sales = function(selected_text) {
      var url;
      selected_text = selected_text.replace(/%/g, "").replace(/&/g, "");
      url = URL + "/sales/search_result?sub_firm[l_firm_name]=" + selected_text + '&sub_firm[name_only]=1' + '&sub_firm[from_top]=1&from_source=search_plugin'
      window.open(url);
      return jQuery("#reach-plugin-control-panel").remove();
  };


  RCC_REACH.mouseup = function(evt) {
    var html, rX, rY, selected_text;
    if (jQuery(evt.target).parents('#reach-plugin-control-panel').length > 0) {
      return;
    }
    if (jQuery("#reach-plugin-control-panel").length === 0) {
        jQuery('body').append('<div id="reach-plugin-control-panel" style="z-index: 99999; display: none"></div>');
        html = "<div><button id='btn-search-firm'>搜索公司名</button><br><button id='btn-search-contact'>搜索联系电话</button></div> ";
        jQuery('#reach-plugin-control-panel').html(html).fadeOut().fadeIn();
    }
    RCC_REACH.redirect_result = true;
    selected_text = window.getSelection().toString();
    selected_text.split('').map = function(str) {
        if ("()+-/:'@\#$\\!~^&*=;.".split("").indexOf(str) >= 0) {
            alert(str);
            return RCC_REACH.redirect_result = false;
        }
    };
    if (RCC_REACH.redirect_result) {
        if ($(window).height() - evt.pageY < 106) {
            rY = evt.pageY - 106;
        } else {
            rY = evt.pageY;
        }
        if ($(window).width() - evt.pageX < 100) {
            rX = evt.pageX - 100;
        } else {
            rX = evt.pageX;
        }
        if (selected_text.length > 0) {
            jQuery("#reach-plugin-control-panel").css('top', rY).css('left', rX);
            jQuery("#reach-plugin-control-panel").css('display', 'block');
            jQuery('#btn-search-firm').click(function() {
                return RCC_REACH.search_text_by_sales(selected_text, 'firm');
            });
            return jQuery('#btn-search-contact').click(function() {
                return RCC_REACH.search_text_by_sales(selected_text, 'contact');
            });
        } else {
            return jQuery("#reach-plugin-control-panel").remove();
        }
    } else {
        return window.open(URL + '/sales/notice_info?from_source=search_plugin');
    }
  };

}).call(this);
