// Generated by CoffeeScript 1.12.7
(function() {
  var targetExtensionId = "dcdjnbgafinaklkiiejdlakcklpfcngd"; // 插件的ID
  var target_data;
  $.getJSON(chrome.extension.getURL('data.json'), function (data){
    target_data = data
  });

  RCC_REACH.search_text = function(selected_text, search_type, options) {
    var reg, url;
    if (search_type === 'baidu') {
      url = "https://www.baidu.com/s?wd=" + selected_text;
    } else {
      selected_text = selected_text.replace(/\(/g, ' ').replace(/\)/g, ' ').replace(/\+/g, ' ')
                                   .replace(/\-/g, ' ').replace(/\//g, ' ').replace(/\:/g, ' ')
                                   .replace(/\'/g, ' ').replace(/\@/g, ' ').replace(/\#/g, ' ')
                                   .replace(/\$/g, ' ').replace(/\!/g, ' ').replace(/\~/g, ' ')
                                   .replace(/\^/g, ' ').replace(/\&/g, ' ').replace(/\*/g, ' ')
                                   .replace(/\=/g, ' ').replace(/\;/g, ' ').replace(/\./g, ' ')
                                   .replace(/\（/g, ' ').replace(/\）/g, ' ')
      reg = new RegExp("^[0-9]*$");
      if (selected_text.length > 2 && ['n', 'p'].indexOf(selected_text[0]) >= 0 && reg.test(selected_text.substring(1, selected_text.length))) {
        if (selected_text[0] === "n") {
          url = "http://research.rccchina.com/#/project_news/show/" + (selected_text.substring(1, selected_text.length))
        }
        if (selected_text[0] === "p") {
          url = "http://in.rccchina.com/projects/show?projectid=" + (selected_text.substring(1, selected_text.length)) + "&from_source=search_plugin";
        }
      } else {
        url = "http://research.rccchina.com/#/quick_search/result?keyword=" + selected_text 
            + "&search_type=" + search_type + "&country_id=" + options['select_country']
            + "&province_id=" + options['select_province'] + "&city_id=" + options['select_city'];
      }
    }
    window.open(url);
    return jQuery("#reach-plugin-control-panel").remove();
  };
  RCC_REACH.mouseup = function(evt) {
    chrome.extension.sendMessage(  {cmd: "来自前台页面的主动调用"}, function(response) {
      if (response != '0'){
        var html, rX, rY, selected_text;
        if (jQuery(evt.target).parents('#reach-plugin-control-panel').length > 0) {
            return;
        }
        if (jQuery("#reach-plugin-control-panel").length === 1){
          jQuery("#reach-plugin-control-panel").remove();
        }
        if (jQuery("#reach-plugin-control-panel").length === 0) {
            jQuery('body').append('<div id="reach-plugin-control-panel"></div>');
            html = "<ul>\
                        <li id='select_city' style=''>\
                            <select name='rcc_select_country' id='rcc_select_country'>\
                                <option value='-2'>全部</option>\
                                <option value='8' selected = 'selected'>中国</option>\
                                <option value='-1'>海外</option>\
                            </select>\
                            <select name='rcc_select_province' id='rcc_select_province' style='width: 80px'>\
                            </select>\
                            <select name='rcc_select_city' id='rcc_select_city' style='width: 110px'>\
                            </select>\
                        </li>\
                        <li id='btn-search-bid-or-project' class= 'search_button'>搜索资源/公告/项目</li>\
                        <li id='btn-search-firm' class='search_button'>搜索公司名</li>\
                        <li id='btn-search-contact' class='search_button'>搜索联系人</li>\
                        <hr /> \
                        <li id='btn-search-baidu' class='search_button'>百度搜索</li>\
                    </ul>"
            jQuery('#reach-plugin-control-panel').html(html).fadeOut().fadeIn();
        }
        RCC_REACH.redirect_result = true;
        selected_text = window.getSelection().toString();
        selected_text.split('').map = function (str) {
            if ("()+-/:'@\#$\\!~^&*=;.".split("").indexOf(str) >= 0) {
                alert(str);
                return RCC_REACH.redirect_result = false;
            }
        };
        if (RCC_REACH.redirect_result) {
            if ($(window).height() - evt.pageY < 106) {
                rY = evt.pageY - 106;
            } else {
                rY = evt.pageY;
            }
            if ($(window).width() - evt.pageX < 100) {
                rX = evt.pageX - 100;
            } else {
                rX = evt.pageX;
            }
            if (selected_text.length > 0) {
                init_province()
                jQuery("#reach-plugin-control-panel").css('top', rY).css('left', rX);
                jQuery("#reach-plugin-control-panel").css('display', 'block');
                jQuery('#btn-search-bid-or-project').click(function () {
                    options = {};
                    options['select_country'] = $('#rcc_select_country').val();
                    options['select_province'] = $('#rcc_select_province').val();
                    options['select_city'] = $('#rcc_select_city').val();
                    return RCC_REACH.search_text(selected_text, 'project_news', options);
                });
                jQuery('#btn-search-firm').click(function () {
                    options = {};
                    options['select_country'] = $('#rcc_select_country').val();
                    options['select_province'] = $('#rcc_select_province').val();
                    options['select_city'] = $('#rcc_select_city').val();
                    return RCC_REACH.search_text(selected_text, 'firm', options);
                });
                jQuery('#btn-search-contact').click(function () {
                    options = {};
                    options['select_country'] = $('#rcc_select_country').val();
                    options['select_province'] = $('#rcc_select_province').val();
                    options['select_city'] = $('#rcc_select_city').val();
                    return RCC_REACH.search_text(selected_text, 'contact', options);
                });
                return jQuery('#btn-search-baidu').click(function () {
                    return RCC_REACH.search_text(selected_text, 'baidu', {});
                });
            } else {
                return jQuery("#reach-plugin-control-panel").remove();
            }
        } else {
            return window.open('http://research.rccchina.com/#/quick_search/result');
        }
      }else if (jQuery("#reach-plugin-control-panel").length !== 0) {
        jQuery("#reach-plugin-control-panel").remove();
      }
    });
  };

  document.addEventListener('mousedown', function(e){
    if (e.button == 2){
        if (jQuery("#reach-plugin-control-panel").length !== 0) {
            jQuery("#reach-plugin-control-panel").remove();
        }
    }
  });
  //
  $(document).delegate('#rcc_select_country', 'change', function(){
    var select_province = jQuery("#rcc_select_province")
    var select_city = jQuery("#rcc_select_city")
    var options = ''
    options += "<option value=''>请选择</option>"
    if (this.value == '8'){
        for(var key in target_data){
            options += "<option value=" + key + ">" + target_data[key][0] + "</option>"
        }
    }
    select_province.html(options)
    select_city.html("<option value=''>请选择</option>")
  });

  $(document).delegate('#rcc_select_province', 'change', function(){
    var select_city = jQuery("#rcc_select_city")
    var options = ''
    options += "<option value=''>请选择</option>"
    if (this.value !== ''){
        var cities = target_data[this.value][1]
        for(var key in cities){
            options += "<option value=" + key + ">" + cities[key] + "</option>"
        }
    }
    select_city.html(options)
  });

  function init_province(){
    var select_province = jQuery("#rcc_select_province")
    var select_city = jQuery("#rcc_select_city")
    var options = ''
    options += "<option value=''>请选择</option>"
    for(var key in target_data){
        options += "<option value=" + key + ">" + target_data[key][0] + "</option>"
    }
    select_province.html(options)
    select_city.html("<option value=''>请选择</option>")
  }
}).call(this);
