// Generated by CoffeeScript 1.12.7
(function() {
  var init_control_panel;

  console.log("Plugin works!");

  init_control_panel = function() {
    return jQuery(document).mouseup(RCC_REACH.mouseup);
  };

  init_control_panel();

}).call(this);
